### ISSUE TITLE
Playground does not work under Linux (macOS?)

### ISSUE THREAD

**Issue by ForLoveOfCats** [pipe01/LICC#10]
`TrueColorConsole.VTConsole` attempts to load the Windows only `kernel32.dll`

![image](https://user-images.githubusercontent.com/30666851/65341707-f26c2480-db9e-11e9-9723-3fb751b32d33.png)

**Comment by pipe01** [comment]
Yeah the VT Console is Windows-exclusive, I should add a check for linux

**Comment by ForLoveOfCats** [comment]
The playground seems to still attempt to load `kernel32.dll`

![image](https://user-images.githubusercontent.com/30666851/65429009-67c83700-dde3-11e9-9881-91db39625281.png)

**Comment by pipe01** [comment]
Should be fixed now

**Comment by ForLoveOfCats** [comment]
It launches but dies when a key is pressed in order to type

![image](https://user-images.githubusercontent.com/30666851/65429313-f76de580-dde3-11e9-8fcd-07f8f20e08c7.png)
Here ^ I simply pressed the 'a' button

**Comment by pipe01** [comment]
I've set it to use the plain text console on Linux for now, but I want to investigate on a solution to use the pretty one
