### ISSUE TITLE
Specify higher C# lang version to build under dotnet

### ISSUE THREAD

**Issue by ForLoveOfCats** [pipe01/LICC#9]
The `.csproj` files need to specify a higher C# language version in order to build under dotnet.

Adding the following to each `.csproj` solves the issue
```
<LangVersion>7.2</LangVersion>
```

**Comment by ForLoveOfCats** [comment]
LICC.Test still causes errors when building with `dotnet build`

![image](https://user-images.githubusercontent.com/30666851/65428823-14ee7f80-dde3-11e9-8997-25662de330f8.png)

**Comment by pipe01** [comment]
Should be fixed with dc718c73cf9bc

**Comment by ForLoveOfCats** [comment]
That's why I commented again, I am on commit `79a04759e7ba3a0c17759954c1605ec7bf28a832`

**Comment by pipe01** [comment]
Yes, but that's an older commit

**Comment by ForLoveOfCats** [comment]
Awesome

**Comment by ForLoveOfCats** [comment]
Yes I realized that
